name: SmokeTests 

on:
  workflow_dispatch:
    inputs:
      ironpdf_version:
        description: 'IronPdf version'
        required: true
        default: '1.0.0-SNAPSHOT'

jobs:
  test_on_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Replace IronPdf LicenseKey
      run: |
        sed -i 's/TEST_LICENSE_KEY/${{ secrets.IRONPDF_LICENSE_KEY }}/g' IronPdf.SmokeTests/src/test/resources/config.properties
    - name: Replace IronPdf version
      run: |
        sed -i 's/please-replace-version/${{ github.event.inputs.ironpdf_version }}/g' IronPdf.SmokeTests/pom.xml
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn --batch-mode -DskipTests package --file IronPdf.SmokeTests/pom.xml
      
    - name: Test
      run: mvn --batch-mode '-Dmaven.test.failure.ignore=true' test --file IronPdf.SmokeTests/pom.xml
      
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: IronPdf.SmokeTests/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
  test_on_ubuntu:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Replace IronPdf LicenseKey
      run: |
        sed -i 's/TEST_LICENSE_KEY/${{ secrets.IRONPDF_LICENSE_KEY }}/g' IronPdf.SmokeTests/src/test/resources/config.properties
    - name: Replace IronPdf version
      run: |
        sed -i 's/please-replace-version/${{ github.event.inputs.ironpdf_version }}/g' IronPdf.SmokeTests/pom.xml
    - name: Install Linux packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y fontconfig libturbojpeg libx11-6 libxext6 libxrender1 libglib2.0-dev libnss3 atk1.0 qt-at-spi libatk-bridge2.0-dev libx11-xcb-dev libxcb-dri3-dev libxcomposite-dev libxdamage1 libdrm-dev libxrandr2 libgbm-dev libasound2-dev libpango1.0-dev
        sudo apt-get install -y software-properties-common fonts-noto fonts-ancient-scripts gsfonts
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install -y gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
        sudo apt-get install -y xvfb libva-dev libgdiplus
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn --batch-mode -DskipTests package --file IronPdf.SmokeTests/pom.xml
      
    - name: Test
      run: mvn --batch-mode '-Dmaven.test.failure.ignore=true' test --file IronPdf.SmokeTests/pom.xml
      
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: IronPdf.SmokeTests/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
